version: "3.9"

x-deploy-defaults: &deploy-defaults
  replicas: 1
  update_config:
    order: start-first
    parallelism: 1
    delay: 5s
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3

services:
  # 프론트
  frontend-portfolio:
    image: ghcr.io/dev-montyoh/frontend-portfolio:latest
    extra_hosts:
      - "redis:host-gateway"
    environment:
      PORT: 80
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    deploy: *deploy-defaults
