name: manual-redeploy-redis

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check out Secrets store
        uses: actions/checkout@v5
        with:
          repository: 'dev-montyoh/secrets-store'
          token: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}
          path: secrets-store

      - name: Load secrets
        uses: ./secrets-store/.github/actions/load-secrets
        with:
          SECRETS_STORE_ACCESS_TOKEN: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}

      - name: ENV to JSON
        id: set_env_json
        run: |
          echo "ENV_VARS_JSON=$(echo '${{ toJSON(env) }}' | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Redeploy Redis to Oracle
        uses: appleboy/ssh-action@v1
        with:
          host: ssh.montyoh.dev
          username: ubuntu
          key_path: ./secrets-store/key/ec2-ssh-key
          script: |
            ENV_JSON='${{ steps.set_env_json.outputs.ENV_VARS_JSON }}'
            eval $(echo "$ENV_JSON" | jq -r '
              to_entries[]
              | select((.key | startswith("GITHUB_") | not) and (.key | startswith("RUNNER_") | not))
              | "export \(.key)=\"\(.value)\";"
            ' | tr -d '\n')

            docker ps -q --filter "name=redis" | xargs -r docker stop
            docker ps -a -q --filter "name=redis" | xargs -r docker rm

            cd /home/ubuntu/app
            curl -L -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository_owner }}/iac-terraform/refs/heads/master/docker-compose.yml
            docker-compose up -d redis
