name: 'Terraform Validate on PR to develop'

on:
  pull_request:
    branches:
      - 'develop'

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  terraform-validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v5

      # 외부 private secrets store 접근
      - name: Check out Secrets store
        uses: actions/checkout@v5
        with:
          repository: 'dev-montyoh/secrets-store'
          token: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}
          path: secrets-store

      # 외부 private secrets store 로드
      - name: Load secrets
        uses: ./secrets-store/.github/actions/load-secrets
        with:
          SECRETS_STORE_ACCESS_TOKEN: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}

      # Terraform 세팅
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      # Terraform 초기화 및 검증
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -no-color -input=false