name: 'Terraform Validate on PR to develop'

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  terraform-validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: 'Checkout'
        uses: actions/checkout@v5

      # Terraform 세팅
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      # Terraform 초기화 및 검증
      - name: 'Terraform Init'
        run: terraform init -backend=false

      - name: 'Terraform Validate'
        run: terraform validate
